version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lambda-run"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-26zkytah02i5"
s3_prefix = "lambda-run"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
